### ISSUE TITLE
Add Data Export to Learn Pages (in SC)

### ISSUE THREAD

**Issue by wendyinnis** [LabKey/cds#478]
#### Rationale
The application currently supports data export of datasets, metadata, variable definitions etc. for both data grids and MAb grids. This story expands that support to include specific learn pages and leverages some previous work in the related pull request.

[Specification](https://docs.google.com/document/d/1QWDYnx_4BdCDxpMvLq3SWYW35DJqXAZExojGYg892aE/edit#heading=h.tu1h6yscsfwq)

####Related Tickets 
[Ticket 45766](https://www.labkey.org/Dataspace/Support%20Tickets/issues-details.view?issueId=45766) - Consistent export button 
[FR 45444](https://www.labkey.org/Dataspace/Feature%20Requests/issues-details.view?issueId=45444)

#### Related PR
- https://github.com/LabKey/cds/pull/475

#### Tasks
- [ ] Changes to existing `CDSExportQueryView` - 5
  - [ ] push down methods into the base class
  - [ ] tbd
- [ ] Conditionally show/hide export button - 2
- [ ] Dimension configuration for data export - 2
- [ ] `CDSLearnQueryView` - 5
- [ ] Post grid information to action -8
  - [ ] filters - 3
  - [ ] variables - 3
  - [ ] metadata - 2
- [ ] Translate learn filters - 3
- [ ] Manual test
- [ ] Code Review -1
- [ ] Merge -0.5

#### Planned hours 

- IPH -25 hrs
- Hours on board- 33 +
- Stories from the same epic ("Plan" and "Consolidate export buttons" in Scrumwise) - 23 hrs
