### ISSUE TITLE
Update the Study pages "Interactive report" section to allow for any URL

### ISSUE THREAD

**Issue by labkey-bpatel** [LabKey/cds#489]
[Spec](https://docs.google.com/document/d/1l5no8D1UizAdquDCx9d9cs--c3K1SjrTkRfRyj2E6EE/edit#)

**Tasks**

- [x] Complete mini spec 0.5h
- [x] Impl plan -1.5 h @labkey-bpatel
- [x] Dev Review -0.5 h @labkey-klum 
- [x] Add more tasks -0.25 @labkey-bpatel
- [x] Add new columns to cds.studyReport and cds.import_studyReport - 1hr
- [x] Identify illegal combinations during an ETL Run - 2 hrs
- [x] Update sample data -  1 hr
- [x] Reconfigure Interactive Reports section - 2 hrs
- [x] Create a PR - 0.25 hr
- [x] Code Review - 1 hr
- [x] Code Review changes -  0 (adj hrs)
- [x] Update Spec - 0.5 hr
- [x] Create test plan - 1 hr
- [x] Manual Test - 2 hr @labkey-sweta 

**Hours**
IPH - 15
Kanban hr-13.5

**Comment by wendyinnis** [comment]
related issue: https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=45789
