### ISSUE TITLE
Dataspace Development 2024

### ISSUE THREAD

**Issue by wendyinnis** [LabKey/cds#637]
### Stories

- [x] [FR48350 Curated groups and plots improvements- Phase II Dev](https://github.com/LabKey/kanban/issues/13)
- [x] (https://github.com/LabKey/kanban/issues/20)
- [x] [Password strengthening - Tests automation](https://github.com/LabKey/kanban/issues/20)
- [x] [24.1.1 Release](https://github.com/LabKey/cds/issues/632)
- [x] [Dataspace] Refactor Learn Group Tab (https://github.com/LabKey/cds/issues/642)
- [x] [Dataspace] Unshown group issue
