### ISSUE TITLE
Dataspace - Update mAb metadata schema

### ISSUE THREAD

**Issue by labkey-klum** [LabKey/cds#654]
[Spec](https://docs.google.com/document/d/1lKl-vOtEKV2wI0W8kPOMUVGGISXk36YK-V2cwdiWkbQ/edit)

**Tasks**
- [x] Implementation plan - 2hr
- [x] Create/update tables - 3hr 
- [x] Delete obsolete queries - 1hr
- [x] Modify dependent queries 
  - [x] `cds.antibody_sequence` - 1hr
  - [x] `cds.MAbMetadata` 
    - [x] `MAbMixMAbMeta.sql`
    - [x] `MAbMixMAbMetaForLearnExport.sql`
    - [x] `alignment_mab_metadata.sql`
    - [x] `ds_mabmetasummary.sql`
    - [x] `sequence_germline_mab_metadata.sql`
  - [x] `cds.alignment` - .5hr
  - [x] `cds.sequence` - 1hr
- [x] Update load application ETL to populate new tables/fields 
  - [x] `cds.donor_metadata` 1hr
  - [x] `cds.donor_mab_sequence` 1hr 
  - [x] intermediate `import_` table clean up
- [x] Ensure container clean up - 1hr
- [x] Fix existing tests
- [x] Update sample data - 1hr
- [x] Create new queries - 1hr
- [ ] Code review - .5hr
